### ISSUE TITLE
Documentation Link Doesn't Work

### ISSUE THREAD

**Issue by dragnilar** [nventive/NuGet.Updater#38]
In the readme there's a link for the documentation: https://github.com/nventive/NuGet.Updater/blob/master/src/NuGet.Updater.Tool/README.md

This link appears to be defunct. 

I was hoping to read more about what this thing does and/or how to use it (since it sounds useful) so it would be appreciated if you could update the documentation.

**Comment by jeromelaban** [comment]
It's actually here, https://github.com/nventive/NuGet.Updater/tree/master/src/NuGet.Updater.Tool

/cc @benventive

**Comment by dragnilar** [comment]
@jeromelaban Much appreciated!
